# Generated by Django 6.0.3 on 2026-04-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام برند')),
                ('is_Active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در  url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='عنوان تگ')),
            ],
            options={
                'verbose_name': 'تگ ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان محصولات')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('short_description', models.CharField(db_index=True, max_length=400, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(null=True, verbose_name='توضیحات تکمیلی محصول')),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products/', verbose_name='تصویر')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیر فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف / حذف نشد')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_modules.productbrand', verbose_name='برند محصول')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductCategory', to='product_modules.productcategory', verbose_name='دسته بندی محصول')),
                ('product_Tag', models.ManyToManyField(to='product_modules.producttag', verbose_name='تگ محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
